name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dalibo/pandocker:xxxxx-test-githubci-xxxxx

    - name: Regression Tests
      run: TAG=xxxxx-test-githubci-xxxxx ./tests/libs/bats/bin/bats tests/docker.bats
#      run: tests/test.sh xxxxx-test-githubci-xxxxx
