name: Stretch Image (obsolete) Regression Tests

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build the Docker image
      run: docker build . --file stretch/Dockerfile --tag dalibo/pandocker:xxxxx-test-githubci-xxxxx

    - name: Regression Tests
      run: TAG=xxxxx-test-githubci-xxxxx VARIANT=stretch ./tests/libs/bats-core/bin/bats tests/docker.bats --tap
